import sys
import os
import numpy as np
import h5py
import re
import contextlib
with contextlib.redirect_stdout(None): #  suppress HITRAN automatic print statement
    from hapi.hapi import partitionSum, moleculeName, isotopologueName

import INTI.helper as help

# The Pycharm Co-pilot was used to write the descriptions for the parameters and return values for the functions in this file.

def create_id_dict():
    """
    Create a dictionary that maps molecules to their HITRAN molecule ID number found here: https://hitran.org/lbl/

    Returns
    -------
    molecule_dict : dict
        Dictionary mapping a given molecule to its HITRAN ID number.

    """

    mol_ID = []
    mol_name = []

    for i in range(1, 55):

        if i == 35:  # Skip 35 since moleculeName(35) throws an error from hapi.py
            continue

        else:
            mol_ID.append(i)
            mol_name.append(moleculeName(i))

        mol_ID.append(35)
        mol_name.append('ClONO2')

    names_and_IDs = zip(mol_name, mol_ID)

    molecule_dict = dict(names_and_IDs)

    return molecule_dict


def check(molecule, isotope):
    """
    Checks if the parameters passed into the summon() function by the user are valid to use with the HITRAN database

    Parameters
    ----------
    molecule : String
        Name of molecule (e.g. H2O).
    isotope : int
        Isotopologue number of the molecule (1 = most common isotopologue, 2 = second most common, etc.).

    Returns
    -------
    None.

    """

    molecule_dict = create_id_dict()
    molecule_id_number = molecule_dict.get(molecule)

    try:  # If we can't create a partition function for the molecule-isotopologue combination, the combination must not exist
        partitionSum(molecule_id_number, isotope, [70, 80], step=1.0)
    except KeyError:
        print(
            "\n ----- This molecule/isotopologue ID combination is not valid in HITRAN. Please try calling the summon() function again. Make sure you enter the ID number of the molecule you want. ----- ")
        print("\n ----- A list of supported molecule IDs can be found here: https://hitran.org/lbl/ -----")
        sys.exit(0)

    return molecule_id_number


def clean_isotope_name(iso_name):
    """
    Replace the isotopologue name generated by HITRAN/HITEMP to match the isotopologue name convention
    used by ExoMol.

    Parameters
    ----------
    iso_name : String
        Name of the isotopologue that is to be replaced.

    Returns
    -------
    iso_name : String
        A differently formatted version of the isotopologue name passed in. Matches ExoMol format.

    """

    # 'H' not followed by lower case letter needs to become '(1H)'
    iso_name = re.sub('H(?![a-z])', '(1H)', iso_name)

    # Number of that atom needs to be enclosed by parentheses ... so '(1H)2' becomes '(1H2)'
    matches = re.findall('[)][0-9]{1}', iso_name)
    for match in matches:
        number = re.findall('[0-9]{1}', match)
        iso_name = re.sub('[)][0-9]{1}', number[0] + ')', iso_name)

    # replace all ')(' with '-'
    iso_name = iso_name.replace(')(', '-')

    return iso_name


def create_pf(mol_ID, iso_ID, folder, T_min=70, T_max=3001, step=1.0):
    """
    Create partition function file using the partitionSum() function already in hapi

    Parameters
    ----------
    mol_ID : int
        Molecule ID number of the given molecule, as given by the first column in HITRAN here: https://hitran.org/lbl/.
    iso_ID : int
        Isotopologue number of the molecule (1 = most common isotopologue, 2 = second most common, etc.).
    folder : String
        Local directory where the partition function file is to be stored.
    T_min : int, optional
        Minimum temperature (K) for which the partition function is computed by hapy.py. The default is 70.
    T_max : int, optional
        Maximum temperature (K) for which the partition function is computed by hapy.py. The default is 3001.
    step : float, optional
        Increment for temperature between T_min and T_max. The default is 1.0.

    Returns
    -------
    None.

    """

    T, Q = partitionSum(mol_ID, iso_ID, [T_min, T_max], step)

    out_file = folder + moleculeName(mol_ID) + '.pf'
    f_out = open(out_file, 'w')
    f_out.write('T | Q \n')
    for i in range(len(T)):
        f_out.write('%.1f %.4f \n' % (T[i], Q[i]))


def create_air_broad(input_dir):
    """
    Create an air broadening file using the downloaded line list

    Parameters
    ----------
    input_dir : String
        Local directory where the broadening file is to be stored.

    Returns
    -------
    None.

    """

    # Instantiate arrays which will be needed for creating air broadening file
    J_lower_all, gamma_air, n_air = (np.array([]) for _ in range(3))
    gamma_air_avg, n_air_avg = (np.array([]) for _ in range(2))

    for file in os.listdir(input_dir):
        if file.endswith('.h5'):
            with h5py.File(input_dir + file, 'r') as hdf:
                # Populate the arrays by reading in each hdf5 file
                J_lower_all = np.append(J_lower_all, np.array(hdf.get('Lower State J')))
                gamma_air = np.append(gamma_air, np.array(hdf.get('Air Broadened Width')))
                n_air = np.append(n_air, np.array(hdf.get('Temperature Dependence of Air Broadening')))

    J_sorted = np.sort(np.unique(J_lower_all))

    for i in range(len(J_sorted)):
        gamma_air_i = np.mean(gamma_air[np.where(J_lower_all == J_sorted[i])])
        n_air_i = np.mean(n_air[np.where(J_lower_all == J_sorted[i])])
        gamma_air_avg = np.append(gamma_air_avg, gamma_air_i)
        n_air_avg = np.append(n_air_avg, n_air_i)

    # Write air broadening file
    out_file = input_dir + 'air.broad'
    f_out = open(out_file, 'w')

    f_out.write('J | gamma_L_0 | n_L \n')

    for i in range(len(J_sorted)):
        f_out.write('%.1f %.4f %.4f \n' % (J_sorted[i], gamma_air_avg[i], n_air_avg[i]))

    f_out.close()


def call_HITRAN(molecule, isotopologue):
    """
    Main function, uses calls to other functions to perform the line list download.

    Parameters
    ----------
    molecule (integer) : int
        Molecular ID number of species as specifed on HITRAN database.
    isotopologue (integer): int
        Isotopologue ID number of species as specifed on HITRAN database.

    Returns
    -------
    None.

    """

    print("\nFetching data from HITRAN. This could take up to an hour so do not stop the download. \nMolecule:",
          moleculeName(molecule), "\nIsotopologue", isotopologueName(molecule, isotopologue), "\n")

    output_folder = help.create_directories(mol_ID=molecule, iso_ID=isotopologue, database='HITRAN')
    create_pf(molecule, isotopologue, output_folder)

    help.download_HITRAN_line_list(molecule, isotopologue, output_folder)

    create_air_broad(output_folder)